defaults:
  - _self_
  - loss: normal
  - model: mlp
  - logger: wandb
  - data: water
  - trainer: trainer_default
  - optimizer: adam
  - estimator: montecarlo

run_mode: sweep
project: counterfactual_overfitting
name: experiments
version: 1
seed: 42
device: cuda