defaults:
  - _self_
  - loader: loader
  - loss: scfe_regularization
  - model: bmlp    # mlp - water or cnn - cifar10
  - logger: wandb
  - data: water
  - trainer: trainer_default
  - optimizer: adam
  - estimator: latent_scfe
  - preprocessor: preprocessing

run_mode: run #sweep or run        
project: counterfactual_overfitting_experiments_new
name: experiments
version: 1
seed: 42
device: cuda