defaults:
  - _self_
  - loader: loader
  - loss: dyn_regularized
  - model: mlp
  - logger: wandb
  - data: water
  - trainer: trainer_default
  - optimizer: sgd
  - estimator: montecarlo

run_mode: run #sweep
project: counterfactual_overfitting
name: experiments
version: 1
seed: 42
device: cuda