defaults:
  - _self_
  - logger: wandb
  - data: water
  - trainer: trainer_default

project: counterfactual_overfitting
name: experiments
version: 1
seed: 42
device: cuda
model_type: MLP
loss_type: dyn_regularized
